//
// WeatherUI
//
// ViewExtension
//
//  Created by Olga Lidman on 2023-02-01
//
//

// This code is generated by ChatGPT :)
import SwiftUI

extension View {
    func navigationBarColor(_ backgroundColor: UIColor) -> some View {
        self.modifier(NavigationBarColor(backgroundColor: backgroundColor))
    }
}

struct NavigationBarColor: ViewModifier {
    var backgroundColor: UIColor
    
    init(backgroundColor: UIColor) {
        self.backgroundColor = backgroundColor
        let coloredAppearance = UINavigationBarAppearance()
        coloredAppearance.configureWithOpaqueBackground()
        coloredAppearance.backgroundColor = backgroundColor
        coloredAppearance.titleTextAttributes = [.foregroundColor: UIColor.white, .font: UIFont.systemFont(ofSize: 20, weight: .semibold)]
        coloredAppearance.largeTitleTextAttributes = [.foregroundColor: UIColor.white]
        UINavigationBar.appearance().standardAppearance = coloredAppearance
        UINavigationBar.appearance().scrollEdgeAppearance = coloredAppearance
        coloredAppearance.shadowImage = UIImage()
    }
    
    func body(content: Content) -> some View {
        ZStack {
            content
        }
    }
}

extension View {
    func makeCircle(radius: Double = 40, color: Color = .dayBlue) -> some View {
        self
        .foregroundColor(.white)
        .frame(width: radius, height: radius)
        .buttonBorderShape(.roundedRectangle(radius: radius / 2))
        .background(Color.dayBlue)
        .cornerRadius(radius / 2)
    }
}
